# fly.toml file generated for notifications-worker on 2022-12-14T15:20:13+05:30

app = "notifications-worker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
dockerfile = "./docker/notifications-worker/Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
